version: '3.2'
services:
  library:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      NODE_ENV: development
    ports:
      - 3000:3000
    volumes:
     - /usr/src/app/node_modules
